FROM sktston/indy-image:py36-1.16-0

ENV ENABLE_PTVSD 0

ADD requirements*.txt ./

RUN pip3 install --no-cache-dir -r requirements.txt -r requirements.dev.txt

USER root
RUN apt update
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
USER indy

ADD aries_cloudagent ./aries_cloudagent
ADD bin ./bin
ADD README.md ./
ADD setup.py ./

RUN pip3 install --no-cache-dir -e .

RUN mkdir logs && chown -R indy:indy logs && chmod -R ug+rw logs

ADD --chown=indy:indy https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh ./
RUN chmod +x ./wait-for-it.sh

ENTRYPOINT ["/bin/bash", "-c", "aca-py \"$@\"", "--"]
